### ISSUE TITLE
Incorrect loop in Go starter kit

### ISSUE THREAD

**Issue by hexaflex-zz** [asimmon/bomberjam-contest#12]
https://github.com/asimmon/bomberjam-contest/blob/3a2edc82b6e5bf906b7f406da4d7ab6a142bdb78/starters/Go/MyBot.go#L42

    game.State.Width

should be 

    game.State.Height

**Comment by asimmon** [comment]
Thank you, I fixed it in https://github.com/asimmon/bomberjam-contest/commit/61cd374ee22d2f5616085e7b82839f923d3ca1eb
