### ISSUE TITLE
Downloads not available because pipeline run too old

### ISSUE THREAD

**Issue by CmdQ** [asimmon/bomberjam-contest#19]
I don't know if downloading from pipeline artifacts is the right way because [right now GitHub doesn't let me](https://github.com/asimmon/bomberjam-contest/actions/runs/1031963354).

From the overview page it says that all three artifacts are expired. They're also not clickable in any way.
![overview](https://user-images.githubusercontent.com/1744960/140748754-1cb4ebed-0922-4aa1-8cbe-c5a4da2ff2f1.png)

And when I select one on the left or in the box, it says more verbosely: “The logs for this run have expired and are no longer available.”

![logs](https://user-images.githubusercontent.com/1744960/140748902-cd9982e4-f11a-4c16-ba64-4c59bf565eb8.png)

**Comment by asimmon** [comment]
Hi @CmdQ, thank you for reporting the issue. Here is a build with new artifacts. I've also updated the link on the website:
https://github.com/asimmon/bomberjam-contest/actions/runs/1438097654
